/* #undef COMPAT_BIO_SPLIT_HAS_BIO_SPLIT_POOL_PARAMETER */
/* #undef COMPAT_BIOSET_CREATE_HAS_THREE_PARAMETERS */
#define COMPAT_HAVE_IS_ERR_OR_NULL
#define COMPAT_HAVE_ATOMIC_IN_FLIGHT
#define COMPAT_HAVE_BIO_BI_DESTRUCTOR
#define COMPAT_HAVE_BIOSET_CREATE_FRONT_PAD
#define COMPAT_HAVE_BLK_QUEUE_MAX_HW_SECTORS
#define COMPAT_HAVE_BLK_QUEUE_MAX_SEGMENTS
/* #undef COMPAT_HAVE_BLKDEV_GET_BY_PATH */
#define COMPAT_HAVE_BOOL_TYPE
#define COMPAT_HAVE_CLEAR_BIT_UNLOCK
#define COMPAT_HAVE_CN_NETLINK_SKB_PARMS
#define COMPAT_HAVE_CTRL_ATTR_MCAST_GROUPS
/* #undef COMPAT_HAVE_DST_GROUPS */
#define COMPAT_HAVE_FIND_NEXT_ZERO_BIT_LE
#define COMPAT_HAVE_FMODE_T
#define COMPAT_HAVE_GENLMSG_MSG_SIZE
#define COMPAT_HAVE_GENLMSG_NEW
#define COMPAT_HAVE_GENLMSG_PUT_REPLY
#define COMPAT_HAVE_GENLMSG_REPLY
#define COMPAT_HAVE_KREF_SUB
/* #undef COMPAT_HAVE_LINUX_BYTEORDER_SWABB_H */
#define COMPAT_HAVE_LIST_SPLICE_TAIL_INIT
/* #undef COMPAT_HAVE_NETLINK_SKB_PARMS_PORTID */
#define COMPAT_HAVE_NLMSG_HDR
#define COMPAT_HAVE_NR_CPU_IDS
#define COMPAT_HAVE_OPEN_BDEV_EXCLUSIVE
#define COMPAT_HAVE_PROC_CREATE_DATA
/* #undef COMPAT_HAVE_RB_AUGMENT_FUNCTIONS */
#define COMPAT_HAVE_SECURITY_NETLINK_RECV
#define COMPAT_HAVE_SOCK_SHUTDOWN
#define COMPAT_HAVE_UMH_WAIT_PROC
/* #undef COMPAT_HAVE_VOID_MAKE_REQUEST */
#define COMPAT_HAVE_VZALLOC
/* #undef COMPAT_INIT_WORK_HAS_THREE_ARGUMENTS */
/* #undef COMPAT_KMAP_ATOMIC_PAGE_ONLY */
/* #undef COMPAT_NEED_GENLMSG_MULTICAST_WRAPPER */
/* #undef COMPAT_USE_BLK_QUEUE_MAX_SECTORS_ANYWAYS */
