
#define ATDR_CTL_DEVICE "/dev/atdr_base"

#define ATDRDEVICECONTROLTYPE 0x9000
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
	((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
	)

enum atdr_ioctl_cmds             
{                               
	ATDRCTL_DEV_CREATE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_BLKDEV_CREATE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_BLKDEV_ATTACH = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_BLKDEV_DESTROY = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_DEV_DESTROY = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_MEMCTL_CREATE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_SET_GRAIN_SIZE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_SET_BITMAP_SIZE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDR_FLIP_BITMAP_AREA = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_GET_GRAIN_SIZE = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x909, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_GET_USER = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS),
	ATDRCTL_BLKDEV_SEARCH = CTL_CODE(ATDRDEVICECONTROLTYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
};
