
#define EBDR_CTL_DEVICE "/dev/ebdr_base"

#define EBDRDEVICECONTROLTYPE 0x9000
#define CTL_CODE( DeviceType, Function, Method, Access ) (                 \
	((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method) \
	)

enum ebdr_ioctl_cmds             
{                               
	EBDRCTL_DEV_CREATE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_BLKDEV_CREATE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_BLKDEV_ATTACH = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_BLKDEV_DESTROY = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_DEV_DESTROY = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_MEMCTL_CREATE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_SET_GRAIN_SIZE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_SET_BITMAP_SIZE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x907, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDR_FLIP_BITMAP_AREA = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x908, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_GET_GRAIN_SIZE = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x909, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_GET_USER = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x910, METHOD_BUFFERED, FILE_ANY_ACCESS),
	EBDRCTL_BLKDEV_SEARCH = CTL_CODE(EBDRDEVICECONTROLTYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
};
