
#define EBDR_CTL_DEVICE "/dev/ebdr_base"
enum ebdr_ioctl_cmds             
{                               
	EBDRCTL_DEV_CREATE,               
	EBDRCTL_BLKDEV_CREATE,     
	EBDRCTL_BLKDEV_ATTACH,
	EBDRCTL_BLKDEV_DESTROY,
	EBDRCTL_DEV_DESTROY,     
	EBDRCTL_MEMCTL_CREATE,
	EBDRCTL_SET_GRAIN_SIZE,
	EBDRCTL_SET_BITMAP_SIZE,
	EBDR_FLIP_BITMAP_AREA,
	EBDRCTL_GET_GRAIN_SIZE = 50,
	EBDRCTL_GET_USER,
  EBDRCTL_BLKDEV_SEARCH
};
